### ISSUE TITLE
Use copy: content instead of temp files?

### ISSUE THREAD

**Issue by jplock** [Servers-for-Hackers/ansible-ssl-example#1]
I was looking through your example and noticed that you are copying the contents of the keys into temporary files, moving them in place, then removing the temp files.  Couldn't you use the `content` property on the `copy` task instead to avoid having to create the temp files?

**Comment by fideloper** [comment]
Probably! I'll check it out. I did a bunch of these all in one go and probably just missed that ability.

Thanks!

**Comment by flecno** [comment]
I used vaulted vars and a `copy` task to write the key file in use of `content: {{ssl_key}}`. This approach looks realy clear in the configuration but I see there is a critical security issue.

If I look into my `/var/log/syslog` file I see this lines:

```
Nov 25 21:12:20 hostname ansible-file: Invoked with directory_mode=None force=False remote_src=None path=/etc/ssl/private/mykey.key owner=root group
=ssl-cert serole=None content=-----BEGIN RSA PRIVATE KEY-----XXXKEYCONTENXXXX-----END RSA PRIVATE KEY-----
```

So ansible logs the property contents on the destination machine. I try to use ssl-encrypted files and save the vault encrypted passphrase in my vars.

**Comment by flecno** [comment]
Oh, ansible 1.8 adds a no_log param: https://github.com/ansible/ansible/pull/2198

**Comment by fideloper** [comment]
I'll check it out, thanks!

**Comment by fideloper** [comment]
Finally got around to this :D  -- Thanks to both of you for your input!
