### ISSUE TITLE
Permissions for ssl directory

### ISSUE THREAD

**Issue by bluetech** [Servers-for-Hackers/ansible-ssl-example#2]
I happened by this repository, and have a couple of comments which might be helpful:
1. The mode parameter for the `file` module is in octal, so it should say `mode=0755` instead of `mode=755` for `/etc/ssl/sfh`.
2. 755 for the ssl directory containing the private key is too permissive IMO, it should be `700`. Note that e.g. nginx workers don't need access to this directory, only the initial daemon.

**Comment by fideloper** [comment]
Thank you, I'll adjust that -

Appreciate the feedback very much!
